name: LinuxStat Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5
      uses: ruby/setup-ruby@21351ecc0a7c196081abca5dc55b08f085efe09a
      with:
        ruby-version: 2.5
    - name: Install dependencies
      run: bundle install
    - name: Run rake install
      run: rake install
    - name: Run tests
      run: linuxstat.rb

    - uses: actions/checkout@v2
    - name: Set up Ruby 2.7
      uses: ruby/setup-ruby@v1.59.1
      with:
        ruby-version: 2.7
    - name: Install dependencies
      run: bundle install
    - name: Run rake install
      run: rake install
    - name: Run tests
      run: linuxstat.rb
